// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// scr_nll
double scr_nll(NumericVector pars, NumericMatrix caps, NumericMatrix traps, NumericMatrix mask);
RcppExport SEXP _scr_scr_nll(SEXP parsSEXP, SEXP capsSEXP, SEXP trapsSEXP, SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type caps(capsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type traps(trapsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(scr_nll(pars, caps, traps, mask));
    return rcpp_result_gen;
END_RCPP
}
// eucdist
NumericVector eucdist(NumericVector point, NumericMatrix traplocations);
RcppExport SEXP _scr_eucdist(SEXP pointSEXP, SEXP traplocationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type point(pointSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type traplocations(traplocationsSEXP);
    rcpp_result_gen = Rcpp::wrap(eucdist(point, traplocations));
    return rcpp_result_gen;
END_RCPP
}
// pointgen
NumericMatrix pointgen(int n, NumericVector xlim, NumericVector ylim);
RcppExport SEXP _scr_pointgen(SEXP nSEXP, SEXP xlimSEXP, SEXP ylimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xlim(xlimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ylim(ylimSEXP);
    rcpp_result_gen = Rcpp::wrap(pointgen(n, xlim, ylim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scr_scr_nll", (DL_FUNC) &_scr_scr_nll, 4},
    {"_scr_eucdist", (DL_FUNC) &_scr_eucdist, 2},
    {"_scr_pointgen", (DL_FUNC) &_scr_pointgen, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_scr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
