# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scr_nll_acoustic <- function(pars, caps, traps, mask, maskDists, nCalls) {
    .Call('_scr_scr_nll_acoustic', PACKAGE = 'scr', pars, caps, traps, mask, maskDists, nCalls)
}

eucdist_nll <- function(points, traplocations) {
    .Call('_scr_eucdist_nll', PACKAGE = 'scr', points, traplocations)
}

scr_nll <- function(pars, caps, traps, mask, maskDists) {
    .Call('_scr_scr_nll', PACKAGE = 'scr', pars, caps, traps, mask, maskDists)
}

pointgen <- function(n = 50L, xlim = as.numeric( c(0, 100)), ylim = as.numeric( c(0, 100))) {
    .Call('_scr_pointgen', PACKAGE = 'scr', n, xlim, ylim)
}

