#' Spatial Capture-Recapture test/example data
#'
#'
#' A dataset containing examples of simple SCR capture histories,
#' an acoustic capture history, trap co-ordinates, and mask point co-ordinates.
#'
#'
#' @docType data
#'
#' @usage data(scr.data)
#'
#' @format A list containing examples of data used in and generated by SCR methods.
#'
#' @keywords datasets
#'
#'
#' @examples
#' data(scr.data)
#' caps = scr.sim(5, 15, scr.data$traps)
"scr.data"
